DNF/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
from authsystem.forms import LoginForm,MyPasswordResetForm,MySetPasswordForm
from django.contrib.auth import views as auth_view

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('core.urls',namespace='core')),
    path('authsystem/', include('authsystem.urls',namespace='authsystem')),
    path('product/', include('product.urls')),
    path('',include("PayOnline.urls", namespace='PayOnline')),
    path('', include('mailapp.urls', namespace='mailapp')),
    
    
     path('password-reset/',auth_view.PasswordResetView.as_view(template_name='authsystem/password_reset.html',form_class=MyPasswordResetForm),name="password_reset"),
     
    path('password-reset/done/',auth_view.PasswordResetDoneView.as_view(template_name='authsystem/password_reset_done.html'),name="password_reset_done"),
     
     path('password-reset-confirm/<uidb64>/<token>',auth_view.PasswordResetConfirmView.as_view(template_name='authsystem/password_reset_confirm.html',form_class=MySetPasswordForm),name='password_reset_confirm'),
     
     path('password-reset-complete',auth_view.PasswordResetCompleteView.as_view(template_name='authsystem/password_reset_complete.html'),name='password_reset_complete'),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

authsystem/urls.py
from django.urls import path
from authsystem import views
from .forms import LoginForm,MyPasswordResetForm,MySetPasswordForm
from django.contrib.auth import views as auth_view



app_name = 'authsystem'
urlpatterns = [
  
     # path('login/',views.logview),
     # path('register/',views.regview),
     path('myregister/',views.register_user,name='myregister'),
     path('login_user/',views.login_user,name='login'),
     path('forgot_password/',views.forgot_password,name='forgot_password'),
     path('logout_user/',views.logout_user,name='logout'),
     
     
     #forgot-password
     path('password-reset/',auth_view.PasswordResetView.as_view(template_name='authsystem/password_reset.html',form_class=MyPasswordResetForm),name="password_reset"),
     
     path('password-reset/done/',auth_view.PasswordResetDoneView.as_view(template_name='authsystem/password_reset_done.html'),name="password_reset_done"),
     
     path('password-reset-confirm/<uidb64>/<token>',auth_view.PasswordResetConfirmView.as_view(template_name='authsystem/password_reset_confirm.html',form_class=MySetPasswordForm),name='password_reset_confirm'),
     
     path('password-reset-complete',auth_view.PasswordResetCompleteView.as_view(template_name='authsystem/password_reset_complete.html'),name='password_reset_complete'),
     
]

authsystem/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser, BaseUserManager, Group, Permission
# Create your models here.


gender_choice = (

    ('male','Male'),
    ('female','Female')
)

class CustomUser(AbstractUser):
    gender_choice = models.CharField(max_length=20, choices=gender_choice,default='male')
    contact = models.CharField(max_length=10, default='') 
    area_name = models.CharField(max_length=200,blank=True,null=True)
    pin_code = models.IntegerField(blank=True,null=True)
    address = models.CharField(max_length=100,blank=True,null=True)
    email = models.EmailField(default='name@email.com', blank=True, null=True)


    # Specify unique related_name attributes to avoid clashes
    groups = models.ManyToManyField(Group, related_name='customuser_groups')
    user_permissions = models.ManyToManyField(Permission, related_name='customuser_permissions')

authsystem/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm,SetPasswordForm,PasswordChangeForm,PasswordResetForm
from .models import CustomUser

class registeruser(UserCreationForm):
     username = forms.CharField( label='Username', max_length=100 ,
                                         widget=forms.TextInput
                                         (attrs={'class': "form-control"}))
     
     first_name = forms.CharField(label='First name', max_length=100 ,
                                         widget=forms.TextInput
                                         (attrs={'class': "form-control"}))

    
     last_name = forms.CharField(label='Last name', max_length=100 ,
                                         widget=forms.TextInput
                                         (attrs={'class': "form-control"}))
     
     


    #  area_name = forms.CharField(label='Area name', max_length=100 ,
    #                                      widget=forms.TextInput
    #                                      (attrs={'class': "form-control"})) 

     
     
     email = forms.EmailField(
        label=("Email"),
        max_length=254,
        widget=forms.EmailInput(attrs={'class': "form-control",'autocomplete': 'email'})
    )
     fields = ['email']
     labels = {'email':'Email ID'}
     widget = {
      'email':forms.EmailInput(attrs={'class':'form-control'}),
     }
     
     password1 = forms.CharField(
        label=("Password"),
        strip=False,
        widget=forms.PasswordInput(attrs={'class': "form-control",'autocomplete': 'new-password'}),
        # help_text=password_validation.password_validators_help_text_html(),
          )
     password2 = forms.CharField(
        label=("Password confirmation"),
        widget=forms.PasswordInput(attrs={'class': "form-control",'autocomplete': 'new-password'}),
        strip=False,
        # help_text=_("Enter the same password as before, for verification."),
     )
    #  pin_code = forms.CharField(label='Pincode', max_length=100 ,
    #                                      widget=forms.TextInput
    #                                      (attrs={'class': "form-control"})) 


     contact = forms.CharField(label='Contact', max_length=10 ,
                                         widget=forms.TextInput
                                         (attrs={'class': "form-control"}))
     
     address = forms.CharField(label='Address', max_length=100 ,
                                         widget=forms.TextInput
                                         (attrs={'class': "form-control"})) 
          

     class Meta:
          model = CustomUser
          fields = ['username','first_name','last_name','email','password1','password2','contact','address']
         

class LoginForm(AuthenticationForm):
       username = forms.CharField(widget=forms.TextInput(attrs={'class':"form-control" ,'autofocus': True,}))

       password = forms.CharField(
        label=("Password"),
        strip=False,
        widget=forms.PasswordInput(attrs={'class':"form-control" ,'autocomplete': 'current-password'}),
    )
       

class Meta:
        model = CustomUser
        fields = ['username','password']
        
class MySetPasswordForm(SetPasswordForm):
   new_password1 = forms.CharField(label='New Password: ',widget=forms.PasswordInput(attrs={'autocomplete':'current-password','class':'form-control'})
   )
   new_password2 = forms.CharField(label='Confirm New Password: ',widget=forms.PasswordInput(attrs={'autocomplete':'current-password','class':'form-control'})
   )
   
class MyPasswordResetForm(PasswordResetForm):
   email=forms.EmailField(widget=forms.EmailInput(attrs={'class':'form-control'})) 

authsystem/views.py
from django.shortcuts import redirect,render
from django.forms.forms import Form
from authsystem.forms import registeruser,LoginForm
from django.contrib import messages
from django.contrib.auth import authenticate,login as auth_login,logout
from django.contrib.auth.forms import PasswordResetForm
from .models import CustomUser
from .forms import registeruser

# Create your views here.

def logview(request):
    return render(request,'authsystem/login.html')


def myregister(request):
    return render(request,'authsystem/register.html')






def forgot_password(request):
    if request.method=="POST":
        email=request.POST.get('email')
        query_set=CustomUser.objects.filter(email=email)
        print(query_set)
        if registeruser.email==email:
            return redirect("/")
    return render(request,'authsystem/forgot_password.html')






def register_user(request):
    print('register_user called')
    if request.method == 'POST':
        print('this is post request')
        form = registeruser(request.POST)
        if form.is_valid():
            form.save()
            messages.info(request,"Registered Sucessfully!!")
            return redirect('authsystem:login')
        else:
            messages.error(request,'Form validation error')
    else:
        form = registeruser()
    return render(request,'authsystem/register.html',{'form':form,'messages': messages.get_messages(request)})




def login_user(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']

        user = authenticate(request, username=username, password=password)

        if user is not None:
            auth_login(request, user)
            return redirect('core:home')
        else:
            messages.error(request, "Username or Password is incorrect")
            return redirect('authsystem:login')

    form = LoginForm()
    return render(request, 'authsystem/login.html', {'form': form, 'messages': messages.get_messages(request)})

def logout_user(request):
    logout(request)
    return redirect('authsystem:login')

templates/authsystem/forgot_password.html
{% extends 'core/hf.html' %}
{% load static %}

{% block body %}

<section class="inner_page_head">
   <div class="container_fuild">
      <div class="row">
         <div class="col-md-12">
            <div class="full">
               <h3> 
                  Forgot Password 
               </h3>
            </div>
         </div>
      </div>
   </div>
</section>

<section class="why_section layout_padding">
   <div class="container">
   
      <div class="row">
         <div class="col-lg-8 offset-lg-2">
            <div class="full">
               <form action="." method="post">
                  {% csrf_token %}
                  {{form.as_p}}
                     <input type="email" placeholder="Enter your email address" name="email" required />
                     <input type="submit" value="Submit" />
               </form>
            </div>
         </div>
      </div>
   </div>
</section>

{% endblock %}

templates/authsystem/login.html
{% extends 'core/hf.html' %}
{% load static %}

{% block body %}

<section class="inner_page_head">
   <div class="container_fuild">
      <div class="row">
         <div class="col-md-12">
            <div class="full">
               <h3> 
                  Login 
               </h3>
            </div>
         </div>
      </div>
   </div>
</section>

<section class="why_section layout_padding">
   <div class="container">
   
      <div class="row">
         <div class="col-lg-8 offset-lg-2">
            <div class="full">
               <form action="." method="post">
                  {% if messages %}
                  <div class="alert {% for message in messages %}{% if message.tags == 'error' %}alert-danger{% elif message.tags == 'info' %}alert-success{% endif %}{% endfor %}" role="alert">
                      {% for message in messages %}
                          {{ message }}
                      {% endfor %}
                  </div>
                  {% endif %}
              


                  {% csrf_token %}
                  {{form.as_p}}
                  <a href="{% url 'authsystem:password_reset' %}"  class="text-dangaer"><small><u>Forgot Password?</u></small></a>
                  {% if form.non_field_errors %}
                    {% for error in form.non_field_errors %}
                    <p class="alert alert-danger my-3">{{error}}</p>
                    {% endfor %}
                {% endif %}
                     <input type="submit" value="Submit" />
                     <div class="text-center fw-bold">
                       <small><u>Create New Account?</u><a href="{% url 'authsystem:myregister' %}"  class="text-dangaer">Click here</a></small>                        
                     </div>

               </form>
            </div>
         </div>
      </div>
   </div>
</section>

{% endblock %}

templates/authsystem/password_reset.html
{% extends 'core/hf.html' %}
{% load static %}

{% block body %}

<section class="inner_page_head">
   <div class="container_fuild">
      <div class="row">
         <div class="col-md-12">
            <div class="full">
               <h3> 
                  Reset Password 
               </h3>
            </div>
         </div>
      </div>
   </div>
</section>

<section class="why_section layout_padding">
   <div class="container">
   
      <div class="row">
         <div class="col-lg-8 offset-lg-2">
            <div class="full">
               <form action="" method="post" novalidate class="shadow p-5">
                  {% csrf_token %}
                  {% for fm in form %}
                    {{fm.label_tag}} {{fm}}<small class="text-danger">{{fm.errors|striptags}}</small><br>
                  {% endfor %}
                <input type="submit" value="Submit" />
                <br>
                {% if form.non_field_errors %}
                    {% for error in form.non_field_errors %}
                    <p class="alert alert-danger my-3">{{error}}</p>
                    {% endfor %}
                {% endif %}
               </form>
            </div>
         </div>
      </div>
   </div>
</section>

{% endblock %}

templates/authsystem/password_reset_complete.html
{% extends 'core/hf.html' %}
{% load static %}

{% block body %}

<section class="inner_page_head">
   <div class="container_fuild">
      <div class="row">
         <div class="col-md-12">
            <div class="full">
               <h3> 
                  Reset Password Complete
               </h3>
               
            </div>
         </div>
      </div>
   </div>
</section>

{% endblock %}

templates/authsystem/password_reset_confirm.html
{% extends 'core/hf.html' %}
{% load static %}

{% block body %}

<section class="inner_page_head">
   <div class="container_fuild">
      <div class="row">
         <div class="col-md-12">
            <div class="full">
               <h3> 
                  Confirm Password
               </h3>
            </div>
         </div>
      </div>
   </div>
</section>

<section class="why_section layout_padding">
   <div class="container">
   
      <div class="row">
         <div class="col-lg-8 offset-lg-2">
            <div class="full">
               <form action="" method="post" novalidate class="shadow p-5">
                    {% csrf_token %}
                    {% for fm in form %}
                    {{fm.label_tag}} {{fm}}<small class="text-danger">{{fm.errors|striptags}}</small><br>
                    {% endfor %}
                <input type="submit" value="Submit" />
                <br>
                {% if form.non_field_errors %}
                    {% for error in form.non_field_errors %}
                    <p class="alert alert-danger my-3">{{error}}</p>
                    {% endfor %}
                {% endif %}
               </form>
            </div>
         </div>
      </div>
   </div>
</section>

{% endblock %}

templates/authsystem/password_reset_done.html
{% extends 'core/hf.html' %}
{% load static %}

{% block body %}

<section class="inner_page_head">
   <div class="container_fuild">
      <div class="row">
         <div class="col-md-12">
            <div class="full">
               <h2> 
                  <p>An Email has been sent with instructions <b>please check your Email</b></P>
               </h2>
            </div>
         </div>
      </div>
   </div>
</section>

{% endblock %}

templates/authsystem/register.html
{% extends 'core/hf.html' %}
{% load static %}

{% block body %}

<section class="inner_page_head">
   <div class="container_fuild">
      <div class="row">
         <div class="col-md-12">
            <div class="full">
               <h3> 
                  Register
               </h3>
            </div>
         </div>
      </div>
   </div>
</section>

<section class="why_section layout_padding">
   <div class="container">
      <div class="row">
         <div class="col-lg-8 offset-lg-2">
            <div class="full">
               <form action="." method="POST" class="form">
                  {% csrf_token %}
                  {% if messages %}
                  <div class="alert {% for message in messages %}{% if message.tags == 'error' %}alert-danger{% elif message.tags == 'info' %}alert-success{% endif %}{% endfor %}" role="alert">
                      {% for message in messages %}
                          {{ message }}
                      {% endfor %}
                  </div>
                  {% endif %}
                  {{form.as_p}}
                  <input type="submit" value="Submit" />
                  <!-- <fieldset>
                     <input type="text" placeholder="Enter your full name" name="name" required />
                     <input type="email" placeholder="Enter your email address" name="email" required />
                     <input type="text" placeholder="Enter subject" name="subject" required />
                     <textarea placeholder="Enter your message" required></textarea>
                     <input type="submit" value="Submit" />
                  </fieldset> -->
                  
                  <div class="text-center text-primary fw-bold">
                     <small> <u>Already have an account?</u><a href="{% url 'authsystem:login' %}"  class="text-dangaer">Login here</a></small>
                     <!-- <input type="submit" value="Already have Account Login here" /> -->
                  </div>
<!-- 
                  {% if messages %}
                  {% for msg in messages %}
                  <div class="alert alert-{{msg.tags}}" role="alert">{{msg}}</div>
                  {% endfor %}
                  {% endif %} -->
               </form>
              
            </div>
         </div>
      </div>
   </div>
</section>

{% endblock %}