DNF/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
from authsystem.forms import LoginForm,MyPasswordResetForm,MySetPasswordForm
from django.contrib.auth import views as auth_view

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('core.urls',namespace='core')),
    path('authsystem/', include('authsystem.urls',namespace='authsystem')),
    path('product/', include('product.urls')),
    path('',include("PayOnline.urls", namespace='PayOnline')),
    path('', include('mailapp.urls', namespace='mailapp')),
    
    
     path('password-reset/',auth_view.PasswordResetView.as_view(template_name='authsystem/password_reset.html',form_class=MyPasswordResetForm),name="password_reset"),
     
    path('password-reset/done/',auth_view.PasswordResetDoneView.as_view(template_name='authsystem/password_reset_done.html'),name="password_reset_done"),
     
     path('password-reset-confirm/<uidb64>/<token>',auth_view.PasswordResetConfirmView.as_view(template_name='authsystem/password_reset_confirm.html',form_class=MySetPasswordForm),name='password_reset_confirm'),
     
     path('password-reset-complete',auth_view.PasswordResetCompleteView.as_view(template_name='authsystem/password_reset_complete.html'),name='password_reset_complete'),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

authsystem/urls.py
from django.urls import path
from authsystem import views
from .forms import LoginForm,MyPasswordResetForm,MySetPasswordForm
from django.contrib.auth import views as auth_view



app_name = 'authsystem'
urlpatterns = [
  
     # path('login/',views.logview),
     # path('register/',views.regview),
     path('myregister/',views.register_user,name='myregister'),
     path('login_user/',views.login_user,name='login'),
     path('forgot_password/',views.forgot_password,name='forgot_password'),
     path('logout_user/',views.logout_user,name='logout'),
     
     
     #forgot-password
     path('password-reset/',auth_view.PasswordResetView.as_view(template_name='authsystem/password_reset.html',form_class=MyPasswordResetForm),name="password_reset"),
     
     path('password-reset/done/',auth_view.PasswordResetDoneView.as_view(template_name='authsystem/password_reset_done.html'),name="password_reset_done"),
     
     path('password-reset-confirm/<uidb64>/<token>',auth_view.PasswordResetConfirmView.as_view(template_name='authsystem/password_reset_confirm.html',form_class=MySetPasswordForm),name='password_reset_confirm'),
     
     path('password-reset-complete',auth_view.PasswordResetCompleteView.as_view(template_name='authsystem/password_reset_complete.html'),name='password_reset_complete'),
     
]

core/urls.py
from django.urls import path
from core import views

app_name = 'core'
urlpatterns = [

    path("", views.core,name='home'),
    path("aboutus/", views.aboutus,name='aboutus'),
    # path("contactus/", views.contactus,name='contactus'),
    path("blog/", views.blog,name='blog'),
    path("search/", views.search,name='search'),
    path("profile/", views.profile,name='profile'),

]

product/urls.py
from django.urls import path
from product import views

app_name = 'product'
urlpatterns = [
    path("", views.product,name='product'),
    path("category/<slug:val>", views.category,name='category'),
    path("productdetail/<int:id>", views.productdetail,name='productdetail'),
    path("test/", views.test,name='test'),
    path("carttest/", views.carttest,name='carttest'),

    path("add_to_cart/<int:prod_id>/", views.add_to_cart,name='add_to_cart'),
    path("showcart/", views.showcart,name='showcart'),
    path('product/order_create/', views.order_create, name='order_create'),
    # path('order_create_no_id/<int:prod_id>', views.order_create, name='order_create_no_id'),

    # path('product/order_create/', views.order_create, name='order_create_no_id'),
  
    path('wishlist/<int:product_id>/',views.wishlist_add,name='wishlist'),
    path('wishlist/',views.wishlist_show,name='wishlist_show'),
    path("<int:product_id>/delete/",views.delete_item,name='delete_item'),
    
    path('contactus/', views.contactus, name='contactus'),
    path("payment/",views.payment,name='payment'),

    # path("checkout/",views.checkout,name='checkout')
    
]

core/models.py
from django.db import models

# Create your models here.

core/views.py
from django.shortcuts import render
from authsystem.models import CustomUser
from django.contrib.auth.decorators import login_required
from product.models import ProductItem
# Create your views here.

@login_required(login_url='authsystem:login')
def core(request):
   
    log_user = CustomUser.objects.get(pk = request.user.id)


    context = {
        'detail': log_user,
   
       
    }
    return render(request,'core/home.html',context)

def aboutus(request):
    log_user = CustomUser.objects.get(pk = request.user.id)
    context = {
        'detail': log_user,
    }
    return render(request,'core/aboutus.html',context) 

# def contactus(request):
#     log_user = CustomUser.objects.get(pk = request.user.id)
#     context = {
#         'detail': log_user,
#     }
#     return render(request,'core/contactus.html',context)


def blog(request):
    log_user = CustomUser.objects.get(pk = request.user.id)
    context = {
        'detail': log_user,
    }
    return render(request,'core/blog.html',context)


def search(request):
    query = request.GET.get('query','') # Use request.GET.get('query', '') to get the 'query' parameter value with a default empty string
    print(type(query))
    if not query:
        pass
    else:
        log_user = CustomUser.objects.get(pk = request.user.id)
        product = ProductItem.objects.filter(P_name__icontains=query)
        context = {
            'product': product,
            'detail': log_user,
        }
        return render(request,'core/search.html',context)
    return render(request,'core/search.html')

@login_required(login_url='authsystem:login')
def profile(request):
    log_user = CustomUser.objects.get(pk = request.user.id)

    print(log_user)
    context = {
        'detail': log_user,
    }
    return render(request,'core/profile.html',context)
    

templates/core/hf.html
<!DOCTYPE html>
{% load static %}
<html>

<head>
   <!-- Basic -->
   <meta charset="utf-8" />
   <meta http-equiv="X-UA-Compatible" content="IE=edge" />
   <!-- Mobile Metas -->
   <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
   <!-- Site Metas -->
   <meta name="keywords" content="" />
   <meta name="description" content="" />
   <meta name="author" content="" />
   <link rel="shortcut icon" href="{% static '/images/l2.png' %}" type="">
   <title>DARK N FREED</title>
   <!-- bootstrap core css -->
   <link rel="stylesheet" type="text/css" href="{% static '/css/bootstrap.css' %}" />
   <!-- font awesome style -->
   <link href="{% static '/css/font-awesome.min.css' %}" rel="stylesheet" />
   <!-- Custom styles for this template -->
   <link href="{% static '/css/style.css' %}" rel="stylesheet" />
   <!-- responsive style -->
   <link href="{% static '/css/responsive.css' %}" rel="stylesheet" />
</head>

<body>

   <div class="">
      <!-- header section strats -->
      <header class="header_section">
         <div class="container">
            <nav class="navbar navbar-expand-lg custom_nav-container ">

               <a class="navbar-brand" href="index.html">
                  <img width="150" style="border-radius:10%;" src="{% static '/images/l2.png' %}" alt="#" />
               </a>
               <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                  aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                  <span class=""> </span>
               </button>
               <div class="collapse navbar-collapse" id="navbarSupportedContent">
                  <ul class="navbar-nav">

                     {% if user.is_authenticated %}

                        <li class="nav-item active">
                           <a class="nav-link" href="{% url 'core:home' %}">Home <span class="sr-only">(current)</span></a>
                        </li>

                        <li class="nav-item dropdown">
                           <a class="nav-link dropdown-toggle" href="#" data-toggle="dropdown" role="button"
                              aria-haspopup="true" aria-expanded="true"> <span class="nav-label">Products <span
                                    class="caret"></span></a>
                           <ul class="dropdown-menu">
                              <li><a href="{% url 'product:category' 'M' %}">Man Collections</a></li>
                              <li><a href="{% url 'product:category' 'W' %}">Women Collections</a></li>
                              <li><a href="{% url 'product:category' 'A' %}">All Product</a></li>

                           </ul>
                        </li>
                        <li class="nav-item">
                           <a class="nav-link" href="{% url 'core:blog' %}">Blog</a>
                        </li>

                        <li class="nav-item">
                           <a class="nav-link" href="{% url 'core:aboutus' %}">AboutUs</a>
                        </li>
                        <li class="nav-item">
                           <a class="nav-link" href="{% url 'product:contactus' %}">Contact</a>
                        </li>
                        <form method="GET" action="{% url 'core:search' %}" class="form-inline">
                           {% csrf_token %}
                           <input class="form-control mr-sm-2" type="text" name="query" placeholder="Search product"
                              aria-label="Search">
                           <button class="btn  my-2 my-sm-0 nav_search-btn" type="submit">
                              <!-- <i class="fa fa-search" aria-hidden="true"></i> -->
                           </button>
                        </form>
                        <li class="nav-item dropdown">
                           <a class="nav-link dropdown-toggle" href="#" data-toggle="dropdown" role="button"
                              aria-haspopup="true" aria-expanded="true"> <span class="nav-label"> {{ detail.first_name }}
                                 <span class="caret"></span></a>
                           <ul class="dropdown-menu">
                              <li><a href="{% url 'core:profile' %}">Profile</a></li>  
                              <li><a href="{% url 'product:showcart' %}">Your Cart</a></li>
                              <li><a href="{% url 'product:wishlist_show' %}">Your Wishlist</a></li>
                              <li><a href="{% url 'authsystem:login' %}">Logout</a></li>
                              
                           </ul>
                        </li>
                     {% else %}
                     <li class="nav-item">
                        <a class="nav-link" href="{% url 'authsystem:login' %}">Login</a>
                     </li>
                     <li class="nav-item">
                        <a class="nav-link" href="{% url 'authsystem:myregister' %}">Register</a>
                     </li>
                     {% endif %}
                  </ul>
               </div>
            </nav>
         </div>
      </header>
      <!-- end header section -->
   </div>



   {% block body %}

   {% endblock %}




   <!-- footer start -->
   <footer>
      <div class="container">
         <div class="row">
            <div class="col-md-4">
               <div class="full">
                  <div class="logo_footer">
                     <a href="{% url 'core:home' %}"><img width="210" style="border-radius:10%;" src="{% static '/images/l2.png' %}"
                           alt="#" /></a>
                  </div>
                  <div class="information_f">
                     <p><strong>ADDRESS:</strong> Comming Soon...</p>
                     <p><strong>TELEPHONE:</strong> +91 987 654 3210</p>
                     <p><strong>EMAIL:</strong> darknfreed23@gmail.com</p>
                  </div>
               </div>
            </div>
            <div class="col-md-8">
               <div class="row">
                  <div class="col-md-7">
                     <div class="row">
                        <div class="col-md-6">
                           <div class="widget_menu">
                              <h3>Menu</h3>
                              <ul>
                                 <li><a href="{% url 'core:home' %}">Home</a></li>
                                 <li><a href="{% url 'core:aboutus' %}">About</a></li>
                                 <li><a href="{% url 'core:home' %}">Services</a></li>
                                 <li><a href="{% url 'core:home' %}">Testimonial</a></li>
                                 <li><a href="{% url 'core:blog' %}">Blog</a></li>
                                 <li><a href="{% url 'product:contactus' %}">Contact</a></li>
                              </ul>
                           </div>
                        </div>
                        <div class="col-md-6">
                           <div class="widget_menu">
                              <h3>Account</h3>
                              <ul>
                                 <li><a href="{% url 'core:profile' %}">Account</a></li>
                                 <li><a href="#">Checkout</a></li>
                                 <li><a href="{% url 'authsystem:login' %}">Login</a></li>
                                 <li><a href="{% url 'authsystem:myregister' %}">Register</a></li>
                                 <li><a href="{% url 'product:product' %}">Shopping</a></li>

                              </ul>
                           </div>
                        </div>
                     </div>
                  </div>
                  <div class="col-md-5">
                     <div class="widget_menu">
                        <h3>Newsletter</h3>
                        <div class="information_f">
                           <p>Subscribe by our newsletter and get update protidin.</p>
                        </div>
                        <div class="form_sub">
                           <form>
                              <fieldset>
                                 <div class="field">
                                    <input type="email" placeholder="Enter Your Mail" name="email" />
                                    <input type="submit" value="Subscribe" />
                                 </div>
                              </fieldset>
                           </form>
                        </div>
                     </div>
                  </div>
               </div>
            </div>
         </div>
      </div>
   </footer>
   <!-- footer end -->
   <div class="cpy_">
      <p>© 2023 All Rights Reserved By</a></p>
   </div>
   <!-- jQery -->
   <script src="{% static '/js/jquery-3.4.1.min.js' %}"></script>
   <!-- popper js -->
   <script src="{% static '/js/popper.min.js' %}"></script>
   <!-- bootstrap js -->
   <script src="{% static '/js/bootstrap.js' %}"></script>
   <!-- custom js -->
   <script src="{% static '/js/custom.js' %}"></script>





</body>

</html>

templates/core/index.html
<!DOCTYPE html>
{% load static %}
<html>

<head>
   <!-- Basic -->
   <meta charset="utf-8" />
   <meta http-equiv="X-UA-Compatible" content="IE=edge" />
   <!-- Mobile Metas -->
   <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
   <!-- Site Metas -->
   <meta name="keywords" content="" />
   <meta name="description" content="" />
   <meta name="author" content="" />
   <link rel="shortcut icon" href="{% static '/images/l2.png' %}" type="">
   <title>DARK N FREED</title>
   <!-- bootstrap core css -->
   <link rel="stylesheet" type="text/css" href="{% static '/css/bootstrap.css' %}" />
   <!-- font awesome style -->
   <link href="{% static '/css/font-awesome.min.css' %}" rel="stylesheet" />
   <!-- Custom styles for this template -->
   <link href="{% static '/css/style.css' %}" rel="stylesheet" />
   <!-- responsive style -->
   <link href="{% static '/css/responsive.css' %}" rel="stylesheet" />
</head>

<body>

   <div class="hero_area">
      <!-- header section strats -->
      <header class="header_section">
         <div class="container">
            <nav class="navbar navbar-expand-lg custom_nav-container ">

               <a class="navbar-brand" href="{% url 'core:home' %}">
                  <img width="150" style="border-radius:10%;" src="{% static '/images/l2.png' %}" alt="#" />
               </a>
               <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                  aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                  <span class=""> </span>
               </button>
               <div class="collapse navbar-collapse" id="navbarSupportedContent">
                  <ul class="navbar-nav">

                     {% if user.is_authenticated %}

                     <li class="nav-item active">
                        <a class="nav-link" href="{% url 'core:home' %}">Home <span class="sr-only">(current)</span></a>
                     </li>

                     <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" data-toggle="dropdown" role="button"
                           aria-haspopup="true" aria-expanded="true"> <span class="nav-label">Products <span
                                 class="caret"></span></a>
                        <ul class="dropdown-menu">
                           <li><a href="{% url 'product:category' 'M' %}">Man Collections</a></li>
                           <li><a href="{% url 'product:category' 'W' %}">Women Collections</a></li>
                           <li><a href="{% url 'product:category' 'A' %}">All Product</a></li>

                        </ul>
                     </li>
                     <li class="nav-item">
                        <a class="nav-link" href="{% url 'core:blog' %}">Blog</a>
                     </li>

                     <li class="nav-item">
                        <a class="nav-link" href="{% url 'core:aboutus' %}">AboutUs</a>
                     </li>
                     <li class="nav-item">
                        <a class="nav-link" href="{% url 'product:contactus' %}">Contact</a>
                     </li>
                     <form method="GET" action="{% url 'core:search' %}" class="form-inline">
                        {% csrf_token %}
                        <input class="form-control mr-sm-2" type="text" name="query" placeholder="Search product"
                           aria-label="Search">
                        <button class="btn  my-2 my-sm-0 nav_search-btn" type="submit">
                           <!-- <i class="fa fa-search" aria-hidden="true"></i> -->
                        </button>
                     </form>




                     <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" data-toggle="dropdown" role="button"
                           aria-haspopup="true" aria-expanded="true"> <span class="nav-label"> {{ detail.first_name }}
                              <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                           <li><a href="{% url 'core:profile' %}">Profile</a></li>                           
                           <li><a href="{% url 'product:showcart' %}">Your Cart</a></li>
                           <li><a href="{% url 'product:wishlist_show' %}">Your Wishlist</a></li>
                           <li><a href="{% url 'authsystem:login' %}">Logout</a></li>
                           
                        </ul>
                     </li>
                     {% endif %}
                     {% if not user.is_authenticated %}
                     <li class="nav-item">
                        <a class="nav-link" href="{% url 'authsystem:login' %}">Login</a>
                     </li>
                     <li class="nav-item">
                        <a class="nav-link" href="{% url 'authsystem:myregister' %}">Register</a>
                     </li>
                     {% endif %}
                  </ul>
               </div>
            </nav>
         </div>
      </header>
      <!-- end header section -->

      <!-- slider section -->
      <section class="slider_section ">
         <div class="slider_bg_box">
            <img src="{% static '/images/banner.png' %}" alt="">
         </div>
         <div id="customCarousel1" class="carousel slide" data-ride="carousel">
            <div class="carousel-inner">
               <div class="carousel-item active">
                  <div class="container ">
                     <div class="row">
                        <div class="col-md-7 col-lg-6 ">
                           <div class="detail-box">
                              <h1>
                                 <span>
                                    Sale 10% Off
                                 </span>
                                 <br>
                                 On T-Shirts
                              </h1>
                              <p>
                                 Attention, fashion enthusiasts! We are thrilled to introduce our latest offer that adds
                                 a touch of style to your wardrobe without breaking the bank. It’s the perfect
                                 opportunity to upgrade your fashion game without compromising your budget. </p>
                              <div class="btn-box">
                                 <a href="{% url 'product:category' 'A' %}" class="btn1">
                                    Shop Now
                                 </a>
                              </div>
                           </div>
                        </div>
                     </div>
                  </div>
               </div>
               <div class="carousel-item ">
                  <div class="container ">
                     <div class="row">
                        <div class="col-md-7 col-lg-6 ">
                           <div class="detail-box">
                              <h1>
                                 <span>
                                    Sale 20% Off
                                 </span>
                                 <br>
                                 On Hoddies
                              </h1>
                              <p>
                                 This season, embrace the chill in style with our exclusive hoodie collection, now
                                 available at a fabulous 20% discount! Snuggle up in our high-quality, trendy hoodies.
                                 Hurry, the offer won’t last long. Grab your favorite hoodie today and step out in
                                 comfort and confidence!
                              <div class="btn-box">
                                 <a href="{% url 'product:category' 'A' %}" class="btn1">
                                    Shop Now
                                 </a>
                              </div>
                           </div>
                        </div>
                     </div>
                  </div>
               </div>
               <div class="carousel-item">
                  <div class="container ">
                     <div class="row">
                        <div class="col-md-7 col-lg-6 ">
                           <div class="detail-box">
                              <h1>
                                 <span>
                                    Sale 10% Off
                                 </span>
                                 <br>
                                 for New User
                              </h1>
                              <p>
                                 We're thrilled to have you on board! As a token of our appreciation, all new users can
                                 enjoy an exclusive 10% discount on their first purchase. Dive into our diverse range of
                                 products, find your favorites, and let the savings begin. Happy shopping! </p>
                              <div class="btn-box">
                                 <a href="{% url 'product:category' 'A' %}" class="btn1">
                                    Shop Now
                                 </a>
                              </div>
                           </div>
                        </div>
                     </div>
                  </div>
               </div>
            </div>
            <div class="container">
               <ol class="carousel-indicators">
                  <li data-target="#customCarousel1" data-slide-to="0" class="active"></li>
                  <li data-target="#customCarousel1" data-slide-to="1"></li>
                  <li data-target="#customCarousel1" data-slide-to="2"></li>
               </ol>
            </div>
         </div>
      </section>
      <!-- end slider section -->
   </div>



   {% block body %}

   {% endblock %}




   <!-- footer start -->
   <footer>
      <div class="container">
         <div class="row">
            <div class="col-md-4">
               <div class="full">
                  <div class="logo_footer">
                     <a href="{% url 'core:home' %}"><img width="210" style="border-radius:10%;" src="{% static '/images/l2.png' %}"
                           alt="#" /></a>
                  </div>
                  <div class="information_f">
                     <p><strong>ADDRESS:</strong> Comming Soon...</p>
                     <p><strong>TELEPHONE:</strong> +91 987 654 3210</p>
                     <p><strong>EMAIL:</strong> darknfreed23@gmail.com</p>
                  </div>
               </div>
            </div>
            <div class="col-md-8">
               <div class="row">
                  <div class="col-md-7">
                     <div class="row">
                        <div class="col-md-6">
                           <div class="widget_menu">
                              <h3>Menu</h3>
                              <ul>
                                 <li><a href="{% url 'core:home' %}">Home</a></li>
                                 <li><a href="{% url 'core:aboutus' %}">About</a></li>
                                 <li><a href="{% url 'core:home' %}">Services</a></li>
                                 <li><a href="{% url 'core:home' %}">Testimonial</a></li>
                                 <li><a href="{% url 'core:blog' %}">Blog</a></li>
                                 <li><a href="{% url 'product:contactus' %}">Contact</a></li>
                              </ul>
                           </div>
                        </div>
                        <div class="col-md-6">
                           <div class="widget_menu">
                              <h3>Account</h3>
                              <ul>
                                 <li><a href="{% url 'core:profile' %}">Account</a></li>
                                 <li><a href="#">Checkout</a></li>
                                 <li><a href="{% url 'authsystem:login' %}">Login</a></li>
                                 <li><a href="{% url 'authsystem:myregister' %}">Register</a></li>
                                 <li><a href="{% url 'product:product' %}">Shopping</a></li>

                              </ul>
                           </div>
                        </div>
                     </div>
                  </div>
                  <div class="col-md-5">
                     <div class="widget_menu">
                        <h3>Newsletter</h3>
                        <div class="information_f">
                           <p>Subscribe by our newsletter and get update protidin.</p>
                        </div>
                        <div class="form_sub">
                           <form>
                              <fieldset>
                                 <div class="field">
                                    <input type="email" placeholder="Enter Your Mail" name="email" />
                                    <input type="submit" value="Subscribe" />
                                 </div>
                              </fieldset>
                           </form>
                        </div>
                     </div>
                  </div>
               </div>
            </div>
         </div>
      </div>
   </footer>
   <!-- footer end -->
   <div class="cpy_">
      <p>© 2023 All Rights Reserved By</a></p>
   </div>
   <!-- jQery -->
   <script src="{% static '/js/jquery-3.4.1.min.js' %}"></script>
   <!-- popper js -->
   <script src="{% static '/js/popper.min.js' %}"></script>
   <!-- bootstrap js -->
   <script src="{% static '/js/bootstrap.js' %}"></script>
   <!-- custom js -->
   <script src="{% static '/js/custom.js' %}"></script>





</body>

</html>

templates/core/profile.html
{% extends 'core/hf.html' %}
{% load static %}

{% block body %}

<!-- inner page section -->
   <section class="inner_page_head">
    <div class="container_fuild">
       <div class="row">
          <div class="col-md-12">
             <div class="full">
                <h3>User Profile</h3>
             </div>
          </div>
       </div>
    </div>
 </section>
 <form class="mt-5 mx-3">
    <div class="form-row">
      <div class="form-group col-md-6">
            <label for="inputPassword4">Username</label>
            <input type="text" class="form-control" id="inputPassword4" name="username" value="{{detail.username}}">
      </div>
      <div class="form-group col-md-6">
        <label for="inputEmail4">Email</label>
        <input type="email" class="form-control" id="inputEmail4" placeholder="Email" name="email" value="{{detail.email}}">
      </div>
    </div>
    <div class="form-row">
        <div class="form-group col-md-6">
          <label for="inputCity">Firstname</label>
          <input type="text" class="form-control" id="inputCity" name="firstname" value="{{detail.first_name}}">
        </div>
        <div class="form-group col-md-4">
          <label for="inputState">Lastname</label>
          <input type="text" class="form-control" id="inputCity" name="lastname" value="{{detail.last_name}}">
        </div>
        <div class="form-group col-md-2">
          <label for="inputZip">Gender</label>
          <input type="text" class="form-control" id="inputZip" name="gender" value="{{detail.gender_choice}}">
        </div>
      </div>
    <div class="form-group">
      <label for="inputAddress">Address</label>
      <input type="text" class="form-control" id="inputAddress" name="address" value="{{detail.address}}">
    </div>
    <div class="form-row">
      <div class="form-group col-md-4">
        <label for="inputCity">Area</label>
        <input type="text" class="form-control" id="inputCity" name="city" value="{{detail.area_name}}">
      </div>
      <div class="form-group col-md-4">
        <label for="inputCity">Contact</label>
        <input type="text" class="form-control" id="inputCity" name="contact" value="{{detail.contact}}">
      </div>
      <div class="form-group col-md-4">
        <label for="inputZip">Pin Code</label>
        <input type="text" class="form-control" id="inputZip" name="pin_code" value="{{detail.pin_code}}">
      </div>
    </div>
  </form>
 <section>

 </section>
 <!-- end inner page section -->

 {% endblock %}