DNF/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
from authsystem.forms import LoginForm,MyPasswordResetForm,MySetPasswordForm
from django.contrib.auth import views as auth_view

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('core.urls',namespace='core')),
    path('authsystem/', include('authsystem.urls',namespace='authsystem')),
    path('product/', include('product.urls')),
    path('',include("PayOnline.urls", namespace='PayOnline')),
    path('', include('mailapp.urls', namespace='mailapp')),
    
    
     path('password-reset/',auth_view.PasswordResetView.as_view(template_name='authsystem/password_reset.html',form_class=MyPasswordResetForm),name="password_reset"),
     
    path('password-reset/done/',auth_view.PasswordResetDoneView.as_view(template_name='authsystem/password_reset_done.html'),name="password_reset_done"),
     
     path('password-reset-confirm/<uidb64>/<token>',auth_view.PasswordResetConfirmView.as_view(template_name='authsystem/password_reset_confirm.html',form_class=MySetPasswordForm),name='password_reset_confirm'),
     
     path('password-reset-complete',auth_view.PasswordResetCompleteView.as_view(template_name='authsystem/password_reset_complete.html'),name='password_reset_complete'),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

PayOnline/urls.py
from unicodedata import name
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from PayOnline import views
from django.urls import path
 
app_name = 'donate'
urlpatterns = [
    path('',views.first ,name='first'),
    path('success/' , views.success , name='success'),
    path('home/', views.home , name='home'),
]

PayOnline/models.py
from django.db import models


# Create your models here.
class Pay(models.Model):
    name = models.CharField(max_length= 1000 , blank=True)
    amount = models.CharField(max_length=100 , blank=True)
    email=models.CharField(max_length=100)
    order_id = models.CharField(max_length=1000 )
    paid = models.BooleanField(default=False)

PayOnline/views.py
from django.shortcuts import render

# Create your views here.
from django.shortcuts import render
import razorpay
from product.models import OrderItem 
from django.views.decorators.csrf import csrf_exempt
from django.conf import settings
from django.core.mail import send_mail
from django.template.loader import render_to_string
from authsystem.models import CustomUser
# from weasyprint import HTML
from .models import Pay
import json
def first(request):
    return render(request,'PayOnline/first.html')

def home(request):
    order_item = OrderItem.objects.last()
    log_user = CustomUser.objects.get(pk = request.user.id)
    context = {
        
        'order_item' : order_item,
        'detail': log_user,
     }
    if request.method == "POST":
        name = request.POST.get('name')
        amount =float(request.POST.get('amount'))*100
        email=request.POST.get('email')
        client = razorpay.Client(auth =("rzp_test_ifqXZb84qSL1CP" , "IwSyyaBvXh300nlqM0kqb0ow"))
        payment = client.order.create({'amount':amount, 'currency':'INR',
                              'payment_capture':'1' })
        
        info = Pay(name = name , amount =amount , order_id = payment['id'])
        info.save()
        
        return render(request, 'PayOnline/index.html' ,{'payment':payment})
    return render(request, 'PayOnline/index.html',context)


@csrf_exempt
def success(request):
    
    
    if request.method == "POST":
        a = request.POST
        order_id = ""
        for key , val in a.items():
            if key == "razorpay_order_id":
                order_id = val
                break
    
        user = Pay.objects.filter(order_id = order_id).first()
        user.paid = True
        user.save()
        
        msg_plain=render_to_string('PayOnline/email.txt')
        msg_html=render_to_string('PayOnline/email.html')

        # send_mail("Your donation has been received",msg_plain,settings.EMAIL_HOST_USER,
        #             ["rajlogicrays@gmail.com"],# [user.email],
        #             html_message=msg_html)

    return render(request, "PayOnline/success.html")


# def download_orders(request):
#     #add your invoice url here
#     full_url = request.build_absolute_uri(reverse('orders'))
#     html = HTML(url=full_url)
#     html.write_pdf(target='C:/Users/Asus/Desktop/download/orders.pdf')

#     fs = FileSystemStorage('C:/Users/Asus/Desktop/download')
#     with fs.open('orders.pdf') as pdf:
#         response = HttpResponse(pdf, content_type='application/pdf')
#         response['Content-Disposition'] = 'attachment; filename="orders.pdf"'
#         return response
#     return response

templates/PayOnline/base.html
{% extends 'core/hf.html' %}
{% load static %}

{% block body %}
<!-- 
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Razorpay</title>
    CSS only
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">

</head> -->
<body>
    

    {% block content %}{% endblock %}
   
    



    <!-- JS, Popper.js, and jQuery -->
<!-- <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>

</body>
</html> -->

{% endblock %}

templates/PayOnline/first.html
{% extends 'core/hf.html' %}
{% load static %}

{% block body %}


<!DOCTYPE html>
<html lang="en">
   <head>
      <!-- basic -->
      <meta charset="utf-8">
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <!-- mobile metas -->
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <meta name="viewport" content="initial-scale=1, maximum-scale=1">
      <!-- site metas -->
      <title>memorial</title>
      <meta name="keywords" content="">
      <meta name="description" content="">
      <meta name="author" content="">
      <!-- bootstrap css -->
      <link rel="stylesheet" href="{% static '/css1/bootstrap.min.css' %}">
      <!-- style css -->
      <link rel="stylesheet" href="{% static '/css1/style.css' %}">
      <!-- Responsive-->
      <link rel="stylesheet" href="{% static '/css1/responsive.css' %}">
      <!-- fevicon -->
      <link rel="icon" href="{% static '/images/fevicon.png' %}" type="image/gif" />
      <!-- Scrollbar Custom CSS -->
      <link rel="stylesheet" href="{% static '/css1/jquery.mCustomScrollbar.min.css' %}">
      <!-- Tweaks for older IEs-->
      <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js' %}"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js' %}"></script><![endif]-->
   </head>
   <!-- body -->
   <body class="main-layout home_page">
      <!-- loader  -->
      <div class="loader_bg">
         <div class="loader"><img src="{% static '/images/loading.gif' %}" alt="#" /></div>
      </div>
      <!-- end loader -->
      <!-- header -->
      <header>
         <!-- header inner -->
         <div class="header">
            <div class="container">
               <div class="row">
                  <div class="col-xl-3 col-lg-3 col-md-3 col-sm-3 col logo_section">
                     <div class="full">
                        <div class="center-desk">
                           <div class="logo"> <a href="hf.html"><img src="{% static '/images/logo.png' %}" alt="#"></a> </div>
                        </div>
                     </div>
                  </div>
                  <div class="col-xl-9 col-lg-9 col-md-9 col-sm-9">
                     <div class="menu-area">
                        <div class="limit-box">
                           <nav class="main-menu">
                              <ul class="menu-area-main">
                                 <li class="active"> <a href="index.html">Home</a> </li>
                                 <li> <a href="about.html">About us</a> </li>
                                 <li> <a href="{% url 'home' %}">Donate</a> </li>
                                
                              </ul>
                           </nav>
                        </div>
                     </div>
                  </div>
               </div>
            </div>
         </div>
         
         <!-- end header inner -->
      </header>
      <!-- end header -->
      <section class="slider_section">
         <div id="myCarousel" class="carousel slide banner-main" data-ride="carousel">
            <div class="carousel-inner">
               <div class="carousel-item active">
                  <center><img style="width:90%;height:670px;" class="first-slide" src="{% static '/images/b.png' %}" alt="First slide"></center>
                  <div class="container">
                     <div class="carousel-caption relative">
                        <h1>SUPPORT THE EDUCATION<br>OF A CHILD <h3 style="color:white;"><b>Enabling self-subsistence</b></h3></h1>

                        <div style="background-color:green;" class="button_section"> <a  class="main_bt" href="{% url 'home' %}">Donate</a></div>
                        
                     </div>
                  </div>
               </div>
               
                           </div>
           
         </div>
      </section>
      <!-- about -->
      <div class="about">
         <div class="container">
            <div class="row">
               <div class="col-md-10 offset-md-1">
                  <div class="aboutheading">
                     <h2>About <strong class="black">Us</strong></h2>
                     <span>Memorial, an NGO for poor child education,directly benefitting over 35,00,000 children and their families every year, through more than 900 live welfare projects on education, livelihood and women empowerment.</span>
                  </div>
               </div>
            </div>
            <div class="row border">
               <div class="col-xl-7 col-lg-7 col-md-12 col-sm-12">
                  <div class="about-box">
                     <p>
Education is both the means as well as the end to a better life: the means because it empowers an individual to earn his/her livelihood and the end.

Doubtless, education is the most powerful catalyst for social transformation. But child education cannot be done in isolation. A child will go to school only if the family, particularly the mother, is assured of healthcare and empowered. Moreover, when an elder sibling is relevantly skilled to be employable and begins earning, the journey of empowerment continues beyond the present generation. </p>
                  
                  </div>
               </div>
               <div class="col-xl-5 col-lg-5 col-md-12 col-sm-12">
                  <div class="about-box">
                     <figure><img src="{% static '/images/about.png' %}" alt="img" /></figure>
                  </div>
               </div>
            </div>
         </div>
      </div>
      
      <!-- end about -->
      








      <!-- footer -->
      <footer>
         <div class="footer">
            <div class="container">
               <div class="row pdn-top-30">
                  <div class="col-xl-4 col-lg-4 col-md-4 col-sm-12">
                     <div class="Follow">
                        <h3>Follow Us</h3>
                     </div>
                     <ul class="location_icon">
                        <li> <a href="#"><img src="{% static '/icon/facebook.png' %}"></a></li>
                        <li> <a href="#"><img src="{% static '/icon/Twitter.png' %}"></a></li>
                        <li> <a href="#"><img src="{% static '/icon/linkedin.png' %}"></a></li>
                        <li> <a href="#"><img src="{% static '/icon/instagram.png' %}"></a></li>
                     </ul>
                  </div>
                  <div class="col-xl-8 col-lg-8 col-md-8 col-sm-12">
                     <div class="Follow">
                        <h3>Newsletter</h3>
                     </div>
                     <input class="Newsletter" placeholder="Enter your email" type="Enter your email">
                     <button class="Subscribe">Subscribe</button>
                  </div>
               </div>
            </div>
         </div>
         
      </footer>
      <!-- end footer -->
      <!-- Javascript files-->
      <script src="{% static '/js1/jquery.min.js' %}"></script>
      <script src="{% static '/js1/popper.min.js' %}"></script>
      <script src="{% static '/js1/bootstrap.bundle.min.js' %}"></script>
      <script src="{% static '/js1/jquery-3.0.0.min.js' %}"></script>
      <script src="{% static '/js1/plugin.js' %}"></script>
      <!-- sidebar -->
      <script src="{% static '/js1/jquery.mCustomScrollbar.concat.min.js' %}"></script>
      <script src="{% static '/js1/custom.js' %}"></script>
   </body>
</html>

{% endblock %}

templates/PayOnline/index.html
{% extends "core/hf.html"  %}
{% load static %}
{% block body %}

<style>
  .a{
    height: 400;
    width: 200;
  }
</style>

{% if not payment %}
<div id="app">
<div class="col-6 pt-5  mx-auto ">
<div class="text-center">
<!-- <img src="{% static '/images/pay.jpg' %}"
style="height:200px" class="img-fluid img-reponsive text-center"> -->
<br>
<h4>Go to Online Payment</h4>
</div>

    <form action="{% url 'donate:home' %}" class="m " method="post" target="_blank" >
        {% csrf_token %}
        <div class="form-group pt-4 ">
            <label for="exampleInputEmail1">Your name</label>
            <input  v-model="name" name="name" type="text" class="form-control"
             id="exampleInputEmail1" aria-describedby="emailHelp">
           
          </div>
        

        <div class="form-group">
          <label for="exampleInputPassword1">Amount</label>
          <input type="number"  class="form-control" name="amount"
           id="exampleInputPassword1" value="{{ order_item.get_cost }}">
         
        </div>

        <button class="btn btn-success btn-block" style="background-color: #f7444e;" type="submit">Submit</button>
        </form>
{% endif %}

{% if payment %}
        <div class="container mx-auto text-center mt-4" v-if="name && amount">

            <form action="{% url 'donate:success' %}" method="POST">
                <script
                    src="https://checkout.razorpay.com/v1/checkout.js"
                    data-key="rzp_test_ifqXZb84qSL1CP" // Enter the Test API Key ID generated from Dashboard → Settings → API Keys
                    data-amount="{{payment.amount}}"
                    data-currency="INR"//You can accept international payments by changing the currency code. Contact our Support Team to enable International for your account
                    data-order_id="{{ payment.id }}"//Replace with the order_id generated by you in the backend.
                    data-buttontext="Pay with Razorpay"
                    data-name="DARK N FREED"
                    data-description="Thanks for Order."
                    data-image="{% static '/images/l2.png' %}"
                    data-prefill.name="Manik Sharma"
                    data-prefill.email="5@gmil.com"
                    data-prefill.contact="333333333"
                    data-theme.color="#F37254"
                ></script>
                <input type="hidden" custom="Hidden Element" name="hidden">
                </form>
            </div>
{% endif %}     
        </div>
        


</div>







   


    <script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>

    <script>
        var app = new Vue({
          delimiters: ['[[', ']]'],
          el: '#app',
          data: {
              message: 'Hello Vue!',
              name : null,
              amount : null
              
          },
          methods: {
              greet: function(name) {
                  console.log('Hello from ' + name + '!')
              },
              get : function(){
                console.log(this.name , this.amount)
              }
          },
          watch : {
            amount(){
                console.log(this.amount)
            }
          }
        });
      </script>


<style>
body{
    background :#ffff;
}

</style>
{% endblock %}

templates/PayOnline/success.html
{% extends 'core/hf.html' %}
{% load static %}

{% block body %}



<div class="container mx-auto mt-5 pt-4 text-center">

    <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcTgyobPWtA8sK4FUdJ7v2mVN1k1XYUwsy1q8A&usqp=CAU">

   
    <h2 class="mt-3 pt-4">Your payment has been received!!</h2>
<!--     <a href="#">Invoice</a> -->
    
</div>

<div class="form-group col-md-12">
    <a href="{% url 'core:home' %}"><input type="submit" style="background-color: #f7444e;" class="btn btn-primary pull-right" value="Go to home"></a>
</div> 

{% endblock %}